### PR TITLE
Handle username which does not exist and show on profile

### PR DESCRIPTION
**Pull request by nil1511**

### CODE REVIEW

**Comment by nil1511** [comment]
@adcpm Updated. can you check again?

**Comment by adcpm** [comment]
We should have same styling for every error component (with div > h3) see  https://github.com/adcpm/busy/blob/dev/src/statics/EmptyUserProfile.js

**Comment by nil1511** [comment]
Updated to match styling with EmptyUserProfile.

**Comment by nil1511** [comment]
@p0o  Added DefaultMessage to all components.

**Pull request merged**
