### PR TITLE
Add loading state for messages (#388)

### LINKED ISSUE #388: Add loading state to the messages page

### PR DESCRIPTION
**Pull request by yamadapc**
This closes #388

### CODE REVIEW

**Comment by adcpm** [comment]
Can you remove this issue and the console.log with the object?
image

**Comment by adcpm** [comment]
There should be a parameter `isLoaded` to avoid load multiple time the same request. Actually if i load all the messages on the chat history, everytime if i up, the loading will come up and try to load messages while there is no messages to load.

**Comment by yamadapc** [comment]
There's a `hasMore` parameter, but I've to change it indeed. Also shouldn't be offset based, but based on the last known `uuid`s or timestamps

**Comment by adcpm** [comment]
Yes using uuid would avoid loading duplicate message. It's pretty much what Steem doing on the blockchain (pagination with username + permlink).

**Pull request merged**
