### PR TITLE
Json parse

### LINKED ISSUE #419: Json metadata with twice stringify make post feed links fail
#### Actual behavior

I can't open a post modal if the json_metadata of the post has been parsed twice.

#### How to reproduce

Go here: https://busy.org/hot/steempoll and click on the first story.

### PR DESCRIPTION
**Pull request by adcpm**
Init formatter.jsonParse method and allow string that have been parsed twice.

Close #419

### CODE REVIEW

**Comment by adcpm** [comment]
Thx @nil1511 it's better you're way. I've done the changes.

**Comment by p0o** [comment]
@adcpm did you consider using something [like this](https://www.npmjs.com/package/parse-json), I'm not exactly sure but I think having the `try` in another file will throw error from the wrong place which is making debugging harder.

**Comment by nil1511** [comment]
@p0o Does it handle over stringified data?

**Comment by p0o** [comment]
@nil1511 No I don't think so it was just a suggestion for throwing error better but I think practically it works just like `JSON/parse()`, I don't have a strong preference over this so if you are okay with this approach just go ahead and merge it.

**Pull request merged**
