### PR TITLE
Like Feature

### LINKED ISSUE #139: Like button required features
- should be refactored into redux
- should show the list of users who liked after clicking on the number of likes
- should optimistically update like numbers after clicking on like
- should re-fetch the data of post to update earnings

Mock up by @adcpm 
pasted_image_at_2016_11_17_16_29

### PR DESCRIPTION
**Pull request by p0o**
should fix #139

### CODE REVIEW

**Comment by adcpm** [comment]
Sometime when i click on like icon the button act like the vote hasn't been saved (but i was)
like

**Comment by adcpm** [comment]
Can we know about downvote on the Like list?

**Comment by p0o** [comment]
@adcpm Please check if the reported issues still exist or not. Also it should work fine on single page without list and extra info (that's for another PR)

**Comment by adcpm** [comment]
The previous issue has been solved. There is a new issue with unlike. When i unlike a post and refresh the page, i still see the like button active. 
unlike

**Comment by adcpm** [comment]
Also when 0 like or dislike the tab should not be clickable, comments too.

**Comment by adcpm** [comment]
Oops. When doing "unlike" its actually making a downvote
image

**Comment by adcpm** [comment]
There is an issue for me, the vote now are just incremented and not keep status see vote

**Comment by p0o** [comment]
@adcpm reported errors should be fixed now.

**Comment by adcpm** [comment]
Like button work fine now :). I saw this issue about the tabs:
- If i click on 0 Likes, look like the tab will open empty (it creating 2pixel difference on UI).
- Comment box should not be openable when 0 comment.
- When there is active vote/downvote the tab should be visible (atm if i click on -1 vote its not opening and i cant see the downvote)

**Comment by p0o** [comment]
The problem here is with posts older than payout. Blockchain API is not returning `active_votes` for these posts so that's the reason of inconsistency between the number of likes and its list. We need to check and if the `active_votes` are not loaded we should load them manually. I'm adding that implementation to this PR soon.

**Comment by adcpm** [comment]
PR look's good using Steemit WS. Well done!

**Pull request merged**
